"""DB creation

Revision ID: bb6ea5680453
Revises: 
Create Date: 2023-06-17 15:45:04.638593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6ea5680453'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stepOfDevelopment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fileName', sa.String(), nullable=False),
    sa.Column('converted_id', sa.String(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stage'], ['stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('stage')
    # ### end Alembic commands ###
